server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/secure_users_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=secure-user-management-api

# JWT properties
jwt.secret=c2VjdXJlLXVzZXItbWFuYWdlbWVudC1hcGktc3VwZXItc2VjcmV0LWtleS0yMDI2LWJyYXlhbi1qd3Q=
jwt.expiration=86400000

# Springdoc / Swagger UI config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.syntax-highlight.theme=monokai
